### ISSUE TITLE
rootfs

### ISSUE THREAD

**Issue by ZYecho** [ktock/container-bootfs#2]
suppose that the image B which generated by our image converter `mkimage`, and our original image was named B.

First, when we run a image which blobs are stored on SSH server, we need to specify something like:
```
sudo docker run -it --privileged --device /dev/fuse \
                --volumes-from ${LOCAL_CACHE_NAME} \
                -e BLOB_STORE=ssh://foo@bar/baz \
                -e DROPBEAR_PASSWORD=foobarbaz \
                image-a:latest
```
now the container's rootfs was the image a's roots, right? how it change to the origin image B's rootfs(which made by blobs store on remote)? how to deal with the rootfs's change? does it need to chroot again?

**Comment by ktock** [comment]
@ZYecho Inside `image-a`, there is a *init-like program* which has responsibility to do this task and we call it `boot` program. On boot of `image-a`, the `boot` program fetches B's blobs from the store, constructs B's rootfs, chroots to it, and then executes the original B's ENTRYPOINT binary.
But there are some issues around here as we mentioned in the [TODO list](https://github.com/ktock/container-bootfs#todo). If you have any ideas, please let us know.

**Comment by ZYecho** [comment]
thanks.
